### PR TITLE
Fix shorts

### LINKED ISSUE #210: Bug: Youtube Shorts is not loading the video.
- webOS version: 4.10.0
- Firmware version: 05.40.45
- OTAID: HE_DTV_W19P_AFADATAA
- SoC: k5lp
- Model: 50UM7510PSB

### LINKED ISSUE #211: Not showing Shorts preview/thumbnail.
It's been a while now but when browsing on the home screen, I can only see the title of the Short, not the preview. See pic attached.

### LINKED ISSUE #219: Bug: Short video don't have image just sound
YTAF 0.3.4
webos : 06.10.50

Hello not a big deal but I see there is a 0.3.5 version that will be certainly release soon. Since some weeks (that was not always the case), the youtube short video have no image only a black screen and the sound. I'm not really into short video but I prefer to say it if it can help for the futur update.

### PR DESCRIPTION
**Pull request by fire332**
~~This PR is built on top of #234. That should be dealt with before this one.~~ ~~#234 is merged.~~ Re-based onto main.

Fixes #210, fixes #211, fixes #219

# Changes
- ~~Allow using TypeScript in app code by adding TypeScript support to babel.~~ Cherry-picked into #238.
- Fix thumbnails in the shorts shelf.
- Fix stretched/offset shorts player by changing the screensaver fix to not apply when not using the watch (full-screen player) page.
- Disable "Remove Shorts from subscriptions" by default.

### CODE REVIEW

**Comment by fire332** [comment]
Whoops. Had a brain fart when refactoring the screensaver fix.

**Comment by cremor** [comment]
Thanks for working on this problem!
I've tested your changes (with a build based on #236) any I can indeed see the video of shorts again. But the video is not placed exactly in the correct area. There is a part of black space on the left side of the video area, and the right side of the video is cut off.

**Comment by fire332** [comment]
@cremor can you take a picture?

**Comment by cremor** [comment]
Sure. This is on an OLED C9 with WebOS 4.10.0:
PXL_20241220_160146180 MP

**Comment by cremor** [comment]
It's just a photo I took with my phone. The short video was paused there, but that doesn't make a difference.
The thumbnail, which is visible for a short moment before the short video playback starts, is not cut off. Only the actual video stream is.

**Comment by cremor** [comment]
> It looks more like the video is in the correct spot but the entire UI is offset

I just measured it. The UI is centered correctly. So the white border is exactly in the center of the screen.

**Comment by cremor** [comment]
> It looks more like the video is in the correct spot but the entire UI is offset

You are right. The white border isn't in the center of the screen. The video itself seems to be in the center.
But what could cause this? I never had this problem before the shorts video stopped being shown a few weeks/months back.

**Comment by fire332** [comment]
Do you know how to use the web inspector tool? Can you check the computed styles of the top-most element that's offset incorrectly?

**Comment by cremor** [comment]
No, but I think I could figure it out with a few hints. What software would I use to do that? I've only used WebOS Device Manager to install the app on the TV.

**Comment by fire332** [comment]
You need node.js 22 LTS installed. Then download a copy of this repository and open the folder in terminal. Then run: 

`npm install`
`ares-inspect -a youtube.leanback.v4`

**Comment by cremor** [comment]
It was a bit more complicated than that 😅 I had to install the WebOS CLI tools and setup the device connection for my TV with it. Only then I could use the `ares-inspect` command.

But even then, how do I continue? I opened the shown "Application Debugging" URL in a browser and it showed YouTube under "Inspectable WebContents". But after clicking it I only get an empty page and the browser dev tools only show an empty body tag.

**Comment by fire332** [comment]
Do you have the app launched on ur TV? If you don't, it's not going to work well.

**Comment by cremor** [comment]
Yes, the app was running. I even had a short opened (in paused state).

**Comment by fire332** [comment]
It might be because you're using the CLI tools provided by LG. Try uninstalling it and use the CLI tools that are included by this project. Your terminal must be opened to the project directory and you need to prefix `ares` commands with `npx` for it to work.

**Comment by cremor** [comment]
Same result.
But I noticed an error in the browser dev tools console: `inspector.js:4031  Uncaught TypeError: document.registerElement is not a function`

Seems like this is a deprecated function which is not supported in modern browsers any more: https://webostv.developer.lge.com/faq/2020-05-20-debugging-web-inspector-not-working-chrome-v80
I assume my TV (WebOS version) is too old. But TBH I don't really want to install that IDE or an old browser...

**Comment by fire332** [comment]
You can always try a portable version.

https://google-chrome-portable.en.uptodown.com/windows/download/2171677

**Comment by cremor** [comment]
That "portable installer" doesn't work. It seems like that portalbe Chrome version isn't available any more (the error message contains a 404).

**Comment by cremor** [comment]
Ok, I found a working version at https://portapps.io/app/ungoogled-chromium-portable/#download
Now I can see the HTML in the inspector.
This seems to be the top element of the border around the short video:
grafik
And here are its computed styles:
grafik

**Comment by fire332** [comment]
Can you take a pic of your TV just like last time again but with the edges of your TV clearly visible?

**Comment by cremor** [comment]
Sure:
Screen

**Comment by fire332** [comment]
Your `html5-video-container` dimensions and position matches up with mines so it's definitely the rest of the UI that's offset.

Can you show me the computed styles for the `ytlr-player-focus-ring`? You can find it easily by entering `document.querySelector("ytlr-player-focus-ring")` into the console, then right-click the result -> reveal in elements panel.

**Comment by cremor** [comment]
Computed styles:
grafik

HTML context:
grafik

**Comment by fire332** [comment]
Show me the computed styles for the `<ytlr-shorts-page>` element right above it in your screenshot.

**Comment by cremor** [comment]
This is the last thing I can test with my TV until the holidays are over because I won't be home.

That element seems to cover the whole screen. But here are the computed styles anyway:
grafik

**Comment by fire332** [comment]
Your computed styles match up exactly with mines so the offset theoretically shouldn't be possible. Lemme know when you get back and feel like jumping on this problem again.

I appreciate your help. Happy holidays.

**Comment by victorrrz** [comment]
I tested this on a LG C1 (using webOS 6.4.0) and now shorts are working fine, with the previous version (v0.3.5-rc1) shorts looked bad, the video was out of frame and stretched horizontally.

File: src/screensaver-fix.ts [hunk 1]
```diff
@@ -0,0 +1,87 @@
...
+  if (isPlayerHidden(video)) return;
+
+  const targetWidth = `${window.innerWidth}px`;
+  const targetHeight = `${window.innerHeight}px`;
+  const targetLeft = '0px';
+  const targetTop = '0px';
+
+  /**
+   * Check to see if identical before assignment as some webOS versions will trigger a mutation
+   * mutation event even if the assignment effectively does nothing, leading to an infinite loop.
```
Comment (jospezial) [inline src/screensaver-fix.ts:65]: mutation  mutation double

Comment (fire332) [reply src/screensaver-fix.ts]: Fixed.

**Comment by Gagac44** [comment]
I also have an LG OLED C9 with WebOS 4.9.17. 
In my case, the video is completely dark and you can only hear the sound. When I click OK on a short, the thumbnail appears for approx. 1 second and as soon as the video starts, the picture goes black and you can only hear the sound.

In addition, the thumbnails of the shorts in the menu or in the search are always black.

**Comment by cremor** [comment]
@Gagac44 I assume you are using the normal release build? This is a pull request discussion. Please only comment here if you actually tested the changes from this PR (by building the app yourself).

**Comment by cremor** [comment]
@fire332 I'm back home and just updated to the latest build from your `fix-shorts` branch. I can continue testing/checking styles if you want. (The short video is still offset in the latest build.)

**Comment by fire332** [comment]
Welcome back. Can you enter this into the console and check if the borders are symmetrical?
```js
document.head.appendChild((function(){var x=document.createElement("style");x.innerHTML="* { border: green solid 1px; }";return x;})())
```

**Comment by cremor** [comment]
That is very weird. That command not only shows borders around all elements, but it also moves the shorts video element so that it is placed correctly. The moment I execute the command the shorts video is moved a bit to the left. I've tested this twice to confirm it.

Before executing the command:
before

After:
after

**Comment by useman** [comment]
webos 03.41.05 works fine with this update

**Comment by fire332** [comment]
Is it the video that shifts back or the UI?

**Comment by cremor** [comment]
The video.

**Comment by fire332** [comment]
@cremor can you run the the same command in console but replace the `*` with `* > video`?

**Comment by cremor** [comment]
This also moves the video frame, but this time it's not in the front (so the rounded borders still look fine).
The green border from your command only shows up on the right side of the video frame.

With video frame border selected (you have to zoom in to see the green border on the right side):
border

With something else selected:
no border

**Comment by fire332** [comment]
What happens if you set the border to`0px` width instead of `1px`?

**Comment by cremor** [comment]
Nothing happens when I do this.
And I can even move the video frame back to the wrong position when I execute it with `0px` (after executing it with `1px`).

**Comment by Trepd** [comment]
OLED55C6V
Built IPK from this PR and i have exat same problem as "cremor" in his pics.

**Comment by fire332** [comment]
@cremor does `0.1px` work?

**Comment by cremor** [comment]
`0.1px` looks exactly the same as `1px`.

If this additional border is indeed the fix I suggest to do it with black. That way it is nearly invisible.

**Comment by fire332** [comment]
To be honest, it makes absolutely no sense how adding a border would correct the position of the video player. So I might just do the dirty border hack just for shorts to save my sanity.

**Comment by fire332** [comment]
Can you try:
```js
document.head.appendChild((function(){var x=document.createElement("style");x.innerHTML="* > video { transform: translateZ(0); }";return x;})())
```

**Comment by cremor** [comment]
> To be honest, it makes absolutely no sense how adding a border would correct the position of the video player.

Yeah, me neither. First I thought it's just the process of adding a style and that that somehow triggers a re-layout of the page. But the fact that applying the style with a `0px` border reverts the effect contradicts that.

> Can you try:

That doesn't seem to do anything.

**Comment by fire332** [comment]
Try `box-shadow: black 0px 0px;` instead of the transform.

**Comment by cremor** [comment]
Also does nothing.

**Comment by fire332** [comment]
`1px` for both instead of `0px`?

**Comment by cremor** [comment]
Again nothing.

**Comment by fire332** [comment]
Try:
```js
document.head.appendChild((function(){var x=document.createElement("style");x.innerHTML=".WEB_PAGE_TYPE_SHORTS #html5-video-container { border-bottom: black 1px solid; border-image: url('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7') 30%;}})())
```

**Comment by cremor** [comment]
There is a syntax error with this. I assume you meant the following? But that also doesn't have any visible effect.

```js
document.head.appendChild((function(){var x=document.createElement("style");x.innerHTML=".WEB_PAGE_TYPE_SHORTS #html5-video-container { border-bottom: black 1px solid; border-image: url('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7') 30%;}";return x;})())```

**Comment by fire332** [comment]
Yes I did. Replace the `#` with a `.` as well.

**Comment by cremor** [comment]
Still no visible effect.

**Comment by fire332** [comment]
Try with `video` instead of `#html5-video-container`.

**Comment by cremor** [comment]
Like that? Still has no visible effect.

```js
document.head.appendChild((function(){var x=document.createElement("style");x.innerHTML=".WEB_PAGE_TYPE_SHORTS video { border-bottom: black 1px solid; border-image: url('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7') 30%;}";return x;})())
```

But the following works (moves the video):
```js
document.head.appendChild((function(){var x=document.createElement("style");x.innerHTML=".WEB_PAGE_TYPE_SHORTS video { border: black 1px solid; border-image: url('data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAALAAAAAABAAEAAAIBRAA7') 30%;}";return x;})())
```

I tested all 4 individual border sides, none work. Only the full border works.
Also it only works with `video`, but not with `.html5-video-container`.

**Comment by fire332** [comment]
> I tested all 4 individual border sides, none work. Only the full border works.

This makes absolutely no sense 😭. Thanks for testing.

**Comment by fire332** [comment]
@cremor One final thing. Try:
```js
document.head.appendChild((function(){var x=document.createElement("style");x.innerHTML=".WEB_PAGE_TYPE_SHORTS video { display: block;}";return x;})())
```

**Comment by cremor** [comment]
No effect.

**Comment by fire332** [comment]
Pushed the fix. Can you re-build on this branch again and see if it works?

**Comment by cremor** [comment]
Doesn't work because you added `border-bottom`. If I change this to `border` then it works. I've tested this without dev tools, so I changed the css file and recompiled.

**Comment by fire332** [comment]
Ahh fuck. I swear I used `border`. Don't code after a few drinks 🫠.

**Comment by fire332** [comment]
Try now.

**Comment by cremor** [comment]
I can't see it directly because of the force-push, but you only changed `border-bottom` to `border`, right? Then I don't have to test it again, this is also what I changed and it worked then.

So in my opinion this can now be merged.
